---
- name: Restart CrowdSec
  community.docker.docker_compose_v2:
    project_src: "{{ crowdsec_base_dir }}"
    state: restarted

- name: Restart Bouncer
  ansible.builtin.systemd:
    name: crowdsec-firewall-bouncer
    state: restarted
