$ANSIBLE_VAULT;1.1;AES256
63646237353432386464303938366334653432616561623966313339346266333662326363633936
6266626539343933633961666531306534353333626439360a646532346538396634633561623135
35356130626561373065613165303533376135303830316531613665323062623937663164313032
3136653231363034370a383536333361376338366130643861383032353630316539663261623565
33363034363931633131303330373536653061393139376562303463343466386333316130353433
31636430393665373634623365363335613436616530313936386162336538323966323864643636
64386336666434306639633331366537353331343139623863623932623662326235633433363837
35396335343631316336303836636535323564383466623564663061373836343065353939663365
32336362333833643937626535633462366431386632653838366239373939633037333933343730
35323332386336323262613237386332346130393961643434623133666430373138353337646237
316639666139623866346134613665343364
