---
- name: Ensure Sablier directory exists
  ansible.builtin.file:
    path: "{{ docker_base_dir }}/{{ sablier_service_name }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0755"
  tags: [sablier, filesystem]

- name: Render docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_base_dir }}/{{ sablier_service_name }}/docker-compose.yml"
    mode: "0640"
    owner: "{{ deploy_user }}"
    group: docker
  tags: [sablier, config]

- name: Deploy Sablier Stack
  community.docker.docker_compose_v2:
    project_src: "{{ docker_base_dir }}/{{ sablier_service_name }}"
    state: present
    pull: always
    remove_orphans: true
  become: true
  become_user: "{{ deploy_user }}"
  tags: [sablier, deploy]
