---
# Handler для пересборки Hugo сайта
- name: Rebuild Hugo site
  community.docker.docker_container:
    name: "{{ hugo_builder_container }}"
    state: started
  failed_when: false
  when: hugo_production_mode
