---
- name: Deploy AmneziaWG
  ansible.builtin.include_role:
    name: common
    tasks_from: docker_service
  vars:
    common_docker_service_name: "{{ amnezia_service_name }}"
    common_docker_service_dir: "{{ amnezia_compose_dir }}"
    common_docker_service_templates:
      - src: nginx_default.conf.j2
        dest: "{{ amnezia_config_dir }}/nginx_default.conf"
    common_docker_service_compose_template: "{{ playbook_dir }}/roles/amnezia/templates/docker-compose.yml.j2"
