---
- name: Deploy Vaultwarden
  ansible.builtin.include_role:
    name: utils
    tasks_from: docker_service
  vars:
    utils_docker_service_name: "{{ vaultwarden_service_name }}"
    utils_docker_service_dir: "{{ vaultwarden_compose_dir }}"
    utils_docker_service_data_dirs:
      - "{{ vaultwarden_data_dir }}"
    utils_docker_service_compose_template: "{{ playbook_dir }}/roles/vaultwarden/templates/docker-compose.yml.j2"
