amneziawg_image: "alexishw/amneziawg-web-ui:master"

# Директории
amneziawg_data_dir: "/srv/docker/amneziawg"
amneziawg_compose_dir: "/opt/amneziawg"

# Домен для HTTPS
amneziawg_domain: "vpn.{{ base_domain }}"

# Внутренний порт Nginx
amneziawg_nginx_port: "80"

# Basic auth
amneziawg_nginx_user: "{{ admin_username }}"
amneziawg_nginx_password: "{{ admin_password }}"

# Traefik
amneziawg_entrypoints: "websecure"

# Параметры VPN
amneziawg_auto_start_servers: "true"
amneziawg_default_mtu: "1280"
amneziawg_default_subnet: "10.0.0.0/24"
amneziawg_default_port: "51820"
amneziawg_default_dns: "8.8.8.8,1.1.1.1"
amneziawg_wireguard_port: "51820"
