---
- name: Deploy Syncthing
  ansible.builtin.include_role:
    name: common
    tasks_from: docker_service
  vars:
    common_docker_service_name: "{{ syncthing_service_name }}"
    common_docker_service_dir: "{{ syncthing_compose_dir }}"
    common_docker_service_data_dirs:
      - "{{ syncthing_data_dir }}"
    common_docker_service_compose_template: "{{ playbook_dir }}/roles/syncthing/templates/docker-compose.yml.j2"
